include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    comment_references: ignore
    lines_longer_than_80_chars: ignore

linter:
  rules:
    avoid_js_rounded_ints: false
    public_member_api_docs: false
